title:            SwiftJuggler
description:      Programming Technology Reviews Travel and Life.
disqus_shortname: swiftjuggler
reading_time:     true
words_per_minute: 200
url:              http://blog.swiftjuggler.com #http://0.0.0.0:4000

# Owner/author information
owner:
  name:           Jerric Lyns John
  avatar:         Selfies/avatar.jpg
  bio:            "Maybe I can handle buggin rocket science."
  email:          jerriclynsjohn@swiftjuggler.com
  twitter:        jerriclynsjohn
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  google_plus:   

# Background image to be tiled on all pages
background: 		triangular.png

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-52166822-1    

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown

permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 3

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["vendor", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

prose:
  siteurl: 'http://blog.swiftjuggler.com/'
  relativeLinks: 'http://blog.swiftjuggler.com/links.jsonp'
  media: 'images/revolt'
  rooturl: 'Revolt'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    "":
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      # - name: "title"
      #   field:
      #     element: "text"
      #     label: "Title"
      #     value: ""
      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
      - name: "modified"
        field:
          element: "text"
          label: "Modified on (Eg. 2014-08-13)"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags (Eg. [Blog, ..])"
          value: ""
      - name: "comments"
        field:
          element: "checkbox"
          label: "Enable Comments"
          value: "true"
      - name: "share"
        field:
          element: "checkbox"
          label: "Enable Share"
          value: "true"
